# Generated by Django 6.0.3 on 2026-03-19 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_employee_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRawLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id_on_device', models.CharField(help_text='ID ของพนักงานที่ตั้งค่าในเครื่อง', max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ข้อมูลดิบการลงเวลา',
                'verbose_name_plural': 'ข้อมูลดิบการลงเวลา',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'ปกติ'), ('late', 'มาสาย'), ('early_leave', 'กลับก่อน'), ('absent', 'ขาดงาน')], default='present', max_length=20)),
                ('source', models.CharField(default='device', help_text='device หรือ mobile_gps', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.employee')),
            ],
            options={
                'verbose_name': 'ข้อมูลการเข้างาน',
                'verbose_name_plural': 'ข้อมูลการเข้างาน',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
