# Generated by Django 6.0.3 on 2026-03-17 13:23

import apps.users.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_code'], 'verbose_name': 'พนักงาน', 'verbose_name_plural': 'ข้อมูลพนักงาน'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=80, scale=None, size=[500, 500], upload_to=apps.users.models.get_avatar_upload_path),
        ),
    ]
