# Generated by Django 6.0.3 on 2026-03-18 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_no', models.IntegerField(help_text='งวดที่จ่าย (เช่น 1-24)')),
                ('period_date', models.DateField(help_text='วันสิ้นสุดงวดการจ่าย')),
                ('salary_wage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='เงินเดือน/ค่าแรง')),
                ('ot_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='รวม OT ทุกประเภท')),
                ('incentive', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='เบี้ยขยัน')),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='เงินได้รวม')),
                ('income_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ภาษีเงินได้')),
                ('social_security', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ประกันสังคม')),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='รายจ่ายรวม')),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='เงินได้สุทธิ')),
                ('ytd_net_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='สะสมเงินได้สุทธิ')),
                ('data_json', models.JSONField(help_text='Raw data from Excel (e.g., OT1, OT2, Late, Fuel, YTD stats)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ข้อมูลเงินเดือน',
                'verbose_name_plural': 'ข้อมูลเงินเดือน',
                'ordering': ['-period_date', 'period_no'],
            },
        ),
    ]
