# Generated by Django 6.0.3 on 2026-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payroll_data_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='data_json',
            field=models.JSONField(blank=True, default=dict, help_text='Raw data from Excel (e.g., OT1, OT2, Late, Fuel, YTD stats)', null=True),
        ),
    ]
